#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Orchis-Dark'
ICONS='arcolinux-candy-beauty'
FONT='Noto Sans 11'
CURSOR='Bibata-Modern-Classic'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
    ${SCHEMA} gtk-theme "$THEME"
    ${SCHEMA} icon-theme "$ICONS"
    ${SCHEMA} cursor-theme "$CURSOR"
    ${SCHEMA} font-name "$FONT"
}

apply_themes
